/*
 * DeleteStudentFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package service;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import util.JdbcUtil;

/**
 *
 * @author  __USER__
 */
public class DeleteStudentFrame extends javax.swing.JFrame {

	/** Creates new form DeleteStudentFrame */
	public DeleteStudentFrame() {
		initComponents();
		setLocationRelativeTo(null);
		
		Font font = new Font("Calibri", Font.BOLD, 14);
		
		nameLabel.setFont(font);
		nameLabel.setForeground(Color.red);
		sexLabel.setFont(font);
		sexLabel.setForeground(Color.red);
		ageLabel.setFont(font);
		ageLabel.setForeground(Color.red);

		Connection conn = null;
		PreparedStatement ps = null;
		ResultSet res = null;
		String sql = "select SSN as SSN from student";

		try {
			conn = JdbcUtil.getConn();
			ps = conn.prepareStatement(sql);
			res = ps.executeQuery();

			while (res.next()) {
				jComboBox1.addItem(res.getString("SSN"));
			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(
					getParent(),
					"exception occurs when querying: \r\n error message: "
							+ e.getMessage(), "error message", 0);
		} finally {
			JdbcUtil.close(res, ps, conn);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        deleteButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete a student");

        jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jLabel1.setText("Delete  a  student");

        jLabel2.setText("choose a student to delete：");

        jComboBox1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---select student SSN---" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        backButton.setText("Cancel");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Sex:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Age:");

        nameLabel.setText(null);

        sexLabel.setText(null);

        ageLabel.setText(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel2)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexLabel)
                            .addComponent(ageLabel))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexLabel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(ageLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

	private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// 删除 按钮

		String SSN = jComboBox1.getSelectedItem().toString();
		String sname = nameLabel.getText();
		String sex = sexLabel.getText();
		String age = ageLabel.getText();

		if ("---select student SSN---".equals(SSN)) {
			JOptionPane.showMessageDialog(getParent(), "please select SSN first",
					"warning message", 2);
		} else {

			if (JOptionPane.showConfirmDialog(getParent(),
					"sure to delete \r\n{\r\nName：" + sname + "\r\nSex：" + sex + "\r\nAge："
							+ age + "\r\n} ???", "Check",
					JOptionPane.YES_NO_OPTION, 3) == JOptionPane.YES_OPTION) {

				Connection conn = null;
				PreparedStatement ps = null;
				String sql = "delete from student where SSN = ?";

				try {
					conn = JdbcUtil.getConn();
					conn.setAutoCommit(false);

					ps = conn.prepareStatement(sql);
					ps.setInt(1, Integer.parseInt(SSN));
					ps.executeUpdate();

					conn.commit();
					JOptionPane.showMessageDialog(getParent(), "student 【" + sname
							+ "】 has been deleted successfully", "successful", 1);

					jComboBox1.removeItem(SSN);

				} catch (SQLException e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(
							getParent(),
							"exception occurs: \r\n error message: "
									+ e.getMessage(), "error message", 0);
					try {
						conn.rollback();
					} catch (SQLException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
				} finally {
					JdbcUtil.close(null, ps, conn);
				}
			}
		}
	}

	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {
		// TODO add your handling code here:
		String SSN = jComboBox1.getSelectedItem().toString();

		if (evt.getStateChange() == ItemEvent.SELECTED) {
			if ("---select student SSN---".equals(SSN)) {

				nameLabel.setText("");
				sexLabel.setText("");
				ageLabel.setText("");

			} else {

				Connection conn = null;
				PreparedStatement ps = null;
				ResultSet res = null;
				String sql = "select sname as SN,sex as SEX,age as AGE from student where SSN = ?";

				try {
					conn = JdbcUtil.getConn();

					ps = conn.prepareStatement(sql);
					ps.setInt(1, Integer.parseInt(SSN));
					res = ps.executeQuery();

					res.next();
					nameLabel.setText(res.getString("SN"));
					sexLabel.setText(res.getString("SEX"));
					ageLabel.setText(res.getString("AGE"));

				} catch (SQLException e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(
							getParent(),
							"exception occurs when querying: \r\n error message: "
									+ e.getMessage(), "error message", 0);
				} finally {
					JdbcUtil.close(res, ps, conn);
				}
			}
		}
	}

	private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// 返回 按钮
		this.dispose();
		new MainFrame().setVisible(true);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DeleteStudentFrame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel sexLabel;
    // End of variables declaration//GEN-END:variables

}