/*
 * DeleteCourseFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package service;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import util.JdbcUtil;

/**
 * 
 * @author __USER__
 */
public class DeleteComFrame extends javax.swing.JFrame {

	/** Creates new form DeleteCourseFrame */
	public DeleteComFrame() {
		initComponents();
		setLocationRelativeTo(null);

		courseNameLabel.setFont(new Font("Calibri", Font.BOLD, 14));
		courseNameLabel.setForeground(Color.red);

		Connection conn = null;
		PreparedStatement ps = null;
		ResultSet res = null;
		String sql = "select cid as CID from course";

		try {
			conn = JdbcUtil.getConn();
			ps = conn.prepareStatement(sql);
			res = ps.executeQuery();

			while (res.next()) {
				jComboBox1.addItem(res.getString("CID"));
			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(
					getParent(),
					"exception occurs when querying: \r\n error message: "
							+ e.getMessage(), "error message", 0);
		} finally {
			JdbcUtil.close(res, ps, conn);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        deleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete a course");

        jComboBox1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---select courseID---" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("choose  a  course  to  delete:");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jLabel2.setText("Delete  a  course");

        backButton.setText("Cancel");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Course Name: ");

        courseNameLabel.setText("null");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(courseNameLabel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(courseNameLabel))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {
		// TODO add your handling code here:
		// jComboBox1 触发事件

		String cid = jComboBox1.getSelectedItem().toString();

		if (evt.getStateChange() == ItemEvent.SELECTED) {
			if ("---select courseID---".equals(cid)) {
				courseNameLabel.setText("");
			} else {

				Connection conn = null;
				PreparedStatement ps = null;
				ResultSet res = null;
				String sql = "select cname as CN from course where cid = ?";

				try {
					conn = JdbcUtil.getConn();

					ps = conn.prepareStatement(sql);
					ps.setInt(1, Integer.parseInt(cid));
					res = ps.executeQuery();

					res.next();
					courseNameLabel.setText(res.getString("CN"));

				} catch (SQLException e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(
							getParent(),
							"exception occurs when querying: \r\n error message: "
									+ e.getMessage(), "error message", 0);
				} finally {
					JdbcUtil.close(res, ps, conn);
				}
			}
		}

	}

	private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// 删除 按钮
		String cid = jComboBox1.getSelectedItem().toString();
		String cname = courseNameLabel.getText();

		if ("---select courseID---".equals(cid)) {
			JOptionPane.showMessageDialog(getParent(), "please select course name first",
					"warning message", 2);
		} else {

			if (JOptionPane.showConfirmDialog(getParent(), "sure to delete 【" + cname
					+ "】???", "YES", JOptionPane.YES_NO_OPTION, 3) == JOptionPane.YES_OPTION) {
				Connection conn = null;
				PreparedStatement ps = null;
				String sql = "delete from course where cid = ?";

				try {
					conn = JdbcUtil.getConn();
					conn.setAutoCommit(false);

					ps = conn.prepareStatement(sql);
					ps.setInt(1, Integer.parseInt(cid));
					ps.executeUpdate();

					conn.commit();
					JOptionPane.showMessageDialog(getParent(), "course 【" + cname
							+ "】 has been deleted successfully", "successful", 1);

					jComboBox1.removeItem(cid);

				} catch (SQLException e) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(
							getParent(),
							"exception occurs: \r\n error message: "
									+ e.getMessage(), "error message", 0);
					try {
						conn.rollback();
					} catch (SQLException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
				} finally {
					JdbcUtil.close(null, ps, conn);
				}
			}
		}
	}

	private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// 返回 按钮
		this.dispose();
		new MainFrame().setVisible(true);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DeleteComFrame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}